In [1]:
import pandas as pd
from SD_Neighborhood_Mapping import find_geolocation_ZIP_Code

                     0
91901           Alpine
92065           Ramona
91905        Boulevard
91906            Campo
91902           Bonita
...                ...
92178         Coronado
92179        Otay Mesa
92182          College
92192  University City
92195          College

[131 rows x 1 columns]

In [2]:
def find_ZIP_Code(row):
    if pd.isnull(row['ZIP Code']):
        return find_geolocation_ZIP_Code(row['Location'])
    else:
        return row['ZIP Code']

In [3]:
# Import our .csv file
df = pd.read_csv('../Data/Job_Posting_Data_With_Job_Sectors.csv')

# Create a column of ZIP codes
df['ZIP Code'] = df['Location'].str.extract(r'(\d{5})')
print(df[df['ZIP Code'].isna()].count())

# Use 'Location' column to find additional ZIP codes
df['ZIP Code'] = df.apply(find_ZIP_Code, axis=1)

#temp = df.apply(find_ZIP_Code, axis=1)
#print(temp)
print(df)

Job Title        2888
Company Name     2888
Location         2888
Remote           2888
Salary           2034
Full Time        2888
Part Time        2888
Date Posted      2888
Salary Type      2034
Annual Salary    2033
Job Sector       2524
ZIP Code            0
dtype: int64
                                              Job Title  \
0                            route sales representative
1                                 ultrasound technician
2                      optometric ophthalmic technician
3                                            controller
4                                       account manager
...                                                 ...
8663                 gift card merchandiser   poway, ca
8664  warehouse attendant ~ quick hire, part time, f...
8665                                        housekeeper
8666                                         technician
8667                        junior full stack developer

                  Company Name  \
0      frito lay north america
1        proximity diagnostics
2     imperial beach optometry
3                     filtrous
4                aya corporate
...                        ...
8663         blackhawk network
8664                    lg oss
8665               carte hotel
8666          bmw of san diego
8667                  revature

                                               Location Remote  \
0     San Diego, CA 92123 \n(Kearny Mesa area)\n+1 l...  False
1                                         San Diego, CA  False
2                 Imperial Beach, CA 91932\n+1 location  False
3                                       Poway, CA 92064  False
4                          San Diego, CA\n+18 locations  False
...                                                 ...    ...
8663                   Remote in Poway, CA\n+1 location   True
8664            Chula Vista, CA 91911\n(Southwest area)  False
8665                  San Diego, CA 92101\n+8 locations  False
8666                  San Diego, CA 92111\n+4 locations  False
8667                        San Diego, CA\n+6 locations  False

                        Salary Full Time Part Time Date Posted Salary Type  \
0                 $1179 a week      True     False    1/7/2022        week
1         $1800 - $3200 a week     False      True    1/7/2022        week
2            $10 - $18 an hour      True     False    1/7/2022        hour
3     $100000 - $150000 a year      True     False    1/7/2022        year
4     $100000 - $175000 a year     False     False    1/7/2022        year
...                        ...       ...       ...         ...         ...
8663                       NaN     False      True   2/25/2022         NaN
8664               $15 an hour     False      True   2/25/2022        hour
8665                       NaN      True     False   2/25/2022         NaN
8666                       NaN      True     False   2/25/2022         NaN
8667                       NaN     False     False   2/25/2022         NaN

      Annual Salary                                      Job Sector ZIP Code
0           61308.0                                 Wholesale Trade    92123
1           93600.0  Professional Scientific and Technical Services     None
2           20870.0  Professional Scientific and Technical Services    91932
3          100000.0  Professional Scientific and Technical Services    92064
4          100000.0                           Finance and Insurance     None
...             ...                                             ...      ...
8663            NaN                                 Wholesale Trade    92064
8664        31305.0                  Transportation and Warehousing    91911
8665            NaN                 Accommodation and Food Services    92101
8666            NaN  Professional Scientific and Technical Services    92111
8667            NaN                                     Information     None

[8668 rows x 12 columns]

In [4]:
# TEMP For Ray, see what jobs are in Alpine w/ Salary

alpine_jobs = df[(df['ZIP Code'] == "91901") & (df['Annual Salary'].notnull())]
display(alpine_jobs)

,Job Title,Company Name,Location,Remote,Salary,Full Time,Part Time,Date Posted,Salary Type,Annual Salary,Job Sector,ZIP Code
2664,human resources generalist,"southern indian health council, inc","Alpine, CA 91901",False,$24.08 - $33.55 an hour,True,False,1/19/2022,hour,50088.0,Mining Quarrying and Oil and Gas Extraction,91901
2706,pharmacy technician,"southern indian health council, inc","Alpine, CA 91901",False,$17.85 - $24.27 an hour,True,False,1/19/2022,hour,35479.0,Professional Scientific and Technical Services,91901
3819,nursing supervisor rn,"southern indian health council, inc","Alpine, CA 91901\n+1 location",False,$91664 - $135013 a year,False,False,1/20/2022,year,91664.0,Management of Companies and Enterprises,91901
4816,front end developers,avi web solutions,"Alpine, CA 91901\n•\nRemote",True,Estimated $78.6K – $99.6K a year,True,False,2022-01-25,year,78600.0,NaN,91901
5887,aircraft maintenance technician,global medical response,"Alpine, CA 91901",False,Estimated $44.7K – $56.7K a year,False,False,2022-01-26,year,44700.0,Professional Scientific and Technical Services,91901
5988,vip host,viejas casino & resort,"Alpine, CA 91901",False,Estimated $41.6K – $52.6K a year,False,False,2022-01-26,year,41600.0,Accommodation and Food Services,91901
6161,client advisor,allstate insurance,"Alpine, CA\n+9 locations",False,$60000 - $90000 a year,False,False,2022-01-26,year,60000.0,Retail Trade,91901
6815,"little caesars store manager alpine, ca (sto...",little caesars,"Alpine, CA\n+9 locations",False,From $17 an hour,False,True,2022-01-27,hour,35479.0,Retail Trade,91901
6905,supervisor of table games,viejas casino & resort,"Alpine, CA 91901\n+2 locations",False,Estimated $50.7K – $64.1K a year,True,False,2022-01-27,year,50700.0,Management of Companies and Enterprises,91901
7008,director of facilities,viejas casino & resort,"Alpine, CA 91901\n+1 location",False,Estimated $75.6K – $95.8K a year,True,False,2022-01-27,year,75600.0,Management of Companies and Enterprises,91901

# Group each column by ZIP Code

In [5]:
def find_job_sector(df, sector):
    return sector == df['Job Sector']

In [6]:
# Count job postings, grouped by ZIP code
count = df.groupby(['ZIP Code']).size()
zip_code_count = pd.Series(count, name='Job Openings')

# Find median salary, grouped by ZIP code
median = df.groupby(['ZIP Code'])['Annual Salary'].median()
zip_code_median_salary = pd.Series(median, name='Median Salary')



# Group "Agriculture Forestry Fishing and Hunting" jobs
sector = "Agriculture Forestry Fishing and Hunting"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
# Check this line
count = df.groupby(['ZIP Code'])[sector].sum()
agriculture_forestry_fishing_and_hunting_count = pd.Series(count, name=sector + " jobs")

# Group "Mining Quarrying and Oil and Gas Extraction" jobs
sector = "Mining Quarrying and Oil and Gas Extraction"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
mining_oil_and_gas_count = pd.Series(count, name=sector + " jobs")

# Group "Utilities" jobs
sector = "Utilities"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
utilities_count = pd.Series(count, name=sector + " jobs")

# Group "Construction" jobs
sector = "Construction"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
construction_count = pd.Series(count, name=sector + " jobs")

# Group "Manufacturing" jobs
sector = "Manufacturing"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
manufacturing_count = pd.Series(count, name=sector + " jobs")

# Group "Manufacturing" jobs
sector = "Manufacturing"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
manufacturing_count = pd.Series(count, name=sector + " jobs")

# Group "Wholesale Trade" jobs
sector = "Wholesale Trade"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
wholesale_trade_count = pd.Series(count, name=sector + " jobs")

# Group "Retail Trade" jobs
sector = "Retail Trade"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
retail_trade_count = pd.Series(count, name=sector + " jobs")

# Group "Transportation and Warehousing" jobs
sector = "Transportation and Warehousing"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
transportation_and_warehousing_count = pd.Series(count, name=sector + " jobs")

# Group "Information" jobs
sector = "Information"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
information_count = pd.Series(count, name=sector + " jobs")

# Group "Finance and Insurance" jobs
sector = "Finance and Insurance"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
finance_and_insurance_count = pd.Series(count, name=sector + " jobs")

# Group "Real Estate and Rental and Leasing" jobs
sector = "Real Estate and Rental and Leasing"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
real_estate_and_rental_and_leasing_count = pd.Series(count, name=sector + " jobs")

# Group "Professional Scientific and Technical Services" jobs
sector = "Professional Scientific and Technical Services"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
professional_scientific_and_technical_count = pd.Series(count, name=sector + " jobs")

# Group "Management of Companies and Enterprises" jobs
sector = "Management of Companies and Enterprises"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
management_of_companies_count = pd.Series(count, name=sector + " jobs")

# Group "Administration & Support Waste Management and Remediation" jobs
sector = "Administration & Support Waste Management and Remediation"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
admin_and_waste_management_count = pd.Series(count, name=sector + " jobs")

# Group "Educational Services" jobs
sector = "Educational Services"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
educational_services_count = pd.Series(count, name=sector + " jobs")

# Group "Health Care and Social Assistance" jobs
sector = "Health Care and Social Assistance"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
health_care_and_social_assistance_count = pd.Series(count, name=sector + " jobs")

# Group "Arts Entertainment and Recreation" jobs
sector = "Arts Entertainment and Recreation"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
arts_entertainment_and_recreation_count = pd.Series(count, name=sector + " jobs")

# Group "Accommodation and Food Services" jobs
sector = "Accommodation and Food Services"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
accommodation_and_food_services_count = pd.Series(count, name=sector + " jobs")

# Group "Public Administration" jobs
sector = "Public Administration"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
public_administration_count = pd.Series(count, name=sector + " jobs")

# Group "Other Services (excluding Public Administration)" jobs
sector = "Other Services (excluding Public Administration)"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
other_count = pd.Series(count, name=sector + " jobs")


#TEMP STUFF
# Group "fast food" jobs
sector = "Fast Food"
df[sector] = df.apply(lambda x: find_job_sector(x, sector), axis=1)
count = df.groupby(['ZIP Code'])[sector].sum()
fast_food_count = pd.Series(count, name=sector + " jobs")



print(zip_code_count)
print(zip_code_median_salary)

ZIP Code
91901    17
91902     7
91906     6
91908     1
91909     5
         ..
92182    21
92191     1
92192     1
92195     1
92199     1
Name: Job Openings, Length: 131, dtype: int64
ZIP Code
91901    50394.0
91902    35479.0
91906    35246.0
91908        NaN
91909    41600.0
          ...
92182    44128.0
92191    33392.0
92192    33392.0
92195    33392.0
92199    35200.0
Name: Median Salary, Length: 131, dtype: float64

In [7]:
# Create dataframe from this information
zip_code_aggregates_df = pd.concat([zip_code_count, 
                        zip_code_median_salary,
                        agriculture_forestry_fishing_and_hunting_count,
                        mining_oil_and_gas_count,
                        utilities_count,
                        construction_count,
                        manufacturing_count,
                        wholesale_trade_count,
                        retail_trade_count,
                        transportation_and_warehousing_count,
                        information_count,
                        finance_and_insurance_count,
                        real_estate_and_rental_and_leasing_count,
                        professional_scientific_and_technical_count,
                        management_of_companies_count,
                        admin_and_waste_management_count,
                        educational_services_count,
                        health_care_and_social_assistance_count,
                        arts_entertainment_and_recreation_count,
                        accommodation_and_food_services_count,
                        public_administration_count,
                        other_count,
                        fast_food_count,
                        ], axis=1)

In [8]:
# Create Neighborhood attribute
import os
from SD_Neighborhood_Mapping import find_SD_neighborhood

zip_code_aggregates_df['Neighborhood'] = zip_code_aggregates_df.index.to_series().apply(find_SD_neighborhood)
print(zip_code_aggregates_df)
zip_code_aggregates_df.to_csv('../Aggregates/Zip_Code_Aggregates.csv')

          Job Openings  Median Salary  \
ZIP Code
91901               17        50394.0
91902                7        35479.0
91906                6        35246.0
91908                1            NaN
91909                5        41600.0
...                ...            ...
92182               21        44128.0
92191                1        33392.0
92192                1        33392.0
92195                1        33392.0
92199                1        35200.0

          Agriculture Forestry Fishing and Hunting jobs  \
ZIP Code
91901                                                 0
91902                                                 0
91906                                                 0
91908                                                 0
91909                                                 0
...                                                 ...
92182                                                 0
92191                                                 0
92192                                                 0
92195                                                 0
92199                                                 0

          Mining Quarrying and Oil and Gas Extraction jobs  Utilities jobs  \
ZIP Code
91901                                                    1               0
91902                                                    0               0
91906                                                    0               0
91908                                                    0               0
91909                                                    0               0
...                                                    ...             ...
92182                                                    1               0
92191                                                    0               0
92192                                                    0               0
92195                                                    0               0
92199                                                    0               0

          Construction jobs  Manufacturing jobs  Wholesale Trade jobs  \
ZIP Code
91901                     1                   0                     0
91902                     0                   0                     0
91906                     1                   0                     0
91908                     0                   0                     1
91909                     0                   0                     0
...                     ...                 ...                   ...
92182                     0                   0                     0
92191                     0                   0                     0
92192                     0                   0                     0
92195                     0                   0                     0
92199                     0                   0                     1

          Retail Trade jobs  Transportation and Warehousing jobs  ...  \
ZIP Code                                                          ...
91901                     5                                    0  ...
91902                     0                                    0  ...
91906                     1                                    1  ...
91908                     0                                    0  ...
91909                     1                                    0  ...
...                     ...                                  ...  ...
92182                     1                                    1  ...
92191                     0                                    1  ...
92192                     0                                    1  ...
92195                     0                                    0  ...
92199                     0                                    0  ...

          Management of Companies and Enterprises jobs  \
ZIP Code
91901                                                5
91902                                                1
91906                                                0
91908                                                0
91909                                                0
...                                                ...
92182                                                0
92191                                                0
92192                                                0
92195                                                0
92199                                                0

          Administration & Support Waste Management and Remediation jobs  \
ZIP Code
91901                                                     1
91902                                                     0
91906                                                     0
91908                                                     0
91909                                                     0
...                                                     ...
92182                                                     0
92191                                                     0
92192                                                     0
92195                                                     0
92199                                                     0

          Educational Services jobs  Health Care and Social Assistance jobs  \
ZIP Code
91901                             0                                       0
91902                             2                                       0
91906                             0                                       1
91908                             0                                       0
91909                             0                                       0
...                             ...                                     ...
92182                             3                                       0
92191                             0                                       0
92192                             0                                       0
92195                             0                                       0
92199                             0                                       0

          Arts Entertainment and Recreation jobs  \
ZIP Code
91901                                          0
91902                                          0
91906                                          0
91908                                          0
91909                                          0
...                                          ...
92182                                          0
92191                                          0
92192                                          0
92195                                          0
92199                                          0

          Accommodation and Food Services jobs  Public Administration jobs  \
ZIP Code
91901                                        1                           0
91902                                        0                           0
91906                                        0                           0
91908                                        0                           0
91909                                        0                           1
...                                        ...                         ...
92182                                        0                           7
92191                                        0                           0
92192                                        0                           0
92195                                        0                           0
92199                                        0                           0

          Other Services (excluding Public Administration) jobs  \
ZIP Code
91901                                                     0
91902                                                     0
91906                                                     0
91908                                                     0
91909                                                     0
...                                                     ...
92182                                                     0
92191                                                     0
92192                                                     0
92195                                                     0
92199                                                     0

          Fast Food jobs     Neighborhood
ZIP Code
91901                  0           Alpine
91902                  0           Bonita
91906                  1            Campo
91908                  0           Bonita
91909                  0      Chula Vista
...                  ...              ...
92182                  3          College
92191                  0             None
92192                  0  University City
92195                  0          College
92199                  0             None

[131 rows x 24 columns]

In [9]:
# Create District aggregate DataFrame
neighborhood_aggregates_df = zip_code_aggregates_df.groupby(['Neighborhood']).sum()

# The Median Salary column is incorrect, so we drop it and reaggregate
neighborhood_aggregates_df.pop('Median Salary')
neighborhood_aggregates_df['Median Salary'] = zip_code_aggregates_df.groupby(['Neighborhood'])['Median Salary'].mean()
print(neighborhood_aggregates_df)

                           Job Openings  \
Neighborhood
Allied Gardens, Del Cerro            44
Alpine                               17
Balboa Park                           2
Bonita                                8
Bonsall                               3
...                                 ...
Tecate                                1
Tierrasanta                           5
University City                     108
Valley Center                        21
Vista                               158

                           Agriculture Forestry Fishing and Hunting jobs  \
Neighborhood
Allied Gardens, Del Cerro                                              0
Alpine                                                                 0
Balboa Park                                                            0
Bonita                                                                 0
Bonsall                                                                0
...                                                                  ...
Tecate                                                                 0
Tierrasanta                                                            0
University City                                                        0
Valley Center                                                          0
Vista                                                                  2

                           Mining Quarrying and Oil and Gas Extraction jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                 0
Alpine                                                                    1
Balboa Park                                                               0
Bonita                                                                    0
Bonsall                                                                   0
...                                                                     ...
Tecate                                                                    0
Tierrasanta                                                               0
University City                                                           0
Valley Center                                                             0
Vista                                                                     3

                           Utilities jobs  Construction jobs  \
Neighborhood
Allied Gardens, Del Cerro               1                  1
Alpine                                  0                  1
Balboa Park                             1                  0
Bonita                                  0                  0
Bonsall                                 0                  0
...                                   ...                ...
Tecate                                  0                  0
Tierrasanta                             0                  0
University City                         0                  7
Valley Center                           0                  0
Vista                                  11                  8

                           Manufacturing jobs  Wholesale Trade jobs  \
Neighborhood
Allied Gardens, Del Cerro                   1                     4
Alpine                                      0                     0
Balboa Park                                 0                     0
Bonita                                      0                     1
Bonsall                                     0                     0
...                                       ...                   ...
Tecate                                      0                     0
Tierrasanta                                 0                     1
University City                             0                    10
Valley Center                               1                     0
Vista                                      16                     8

                           Retail Trade jobs  \
Neighborhood
Allied Gardens, Del Cerro                  4
Alpine                                     5
Balboa Park                                1
Bonita                                     0
Bonsall                                    0
...                                      ...
Tecate                                     0
Tierrasanta                                0
University City                           13
Valley Center                              0
Vista                                     22

                           Transportation and Warehousing jobs  \
Neighborhood
Allied Gardens, Del Cerro                                    2
Alpine                                                       0
Balboa Park                                                  0
Bonita                                                       0
Bonsall                                                      0
...                                                        ...
Tecate                                                       1
Tierrasanta                                                  0
University City                                              2
Valley Center                                                0
Vista                                                        8

                           Information jobs  ...  \
Neighborhood                                 ...
Allied Gardens, Del Cerro                 0  ...
Alpine                                    0  ...
Balboa Park                               0  ...
Bonita                                    1  ...
Bonsall                                   0  ...
...                                     ...  ...
Tecate                                    0  ...
Tierrasanta                               1  ...
University City                           9  ...
Valley Center                             0  ...
Vista                                     5  ...

                           Management of Companies and Enterprises jobs  \
Neighborhood
Allied Gardens, Del Cerro                                             4
Alpine                                                                5
Balboa Park                                                           0
Bonita                                                                1
Bonsall                                                               0
...                                                                 ...
Tecate                                                                0
Tierrasanta                                                           0
University City                                                      11
Valley Center                                                         1
Vista                                                                20

                           Administration & Support Waste Management and Remediation jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                  1
Alpine                                                                     1
Balboa Park                                                                0
Bonita                                                                     0
Bonsall                                                                    0
...                                                                      ...
Tecate                                                                     0
Tierrasanta                                                                1
University City                                                            0
Valley Center                                                              1
Vista                                                                      2

                           Educational Services jobs  \
Neighborhood
Allied Gardens, Del Cerro                          2
Alpine                                             0
Balboa Park                                        0
Bonita                                             2
Bonsall                                            3
...                                              ...
Tecate                                             0
Tierrasanta                                        0
University City                                    8
Valley Center                                      0
Vista                                              2

                           Health Care and Social Assistance jobs  \
Neighborhood
Allied Gardens, Del Cerro                                       9
Alpine                                                          0
Balboa Park                                                     0
Bonita                                                          0
Bonsall                                                         0
...                                                           ...
Tecate                                                          0
Tierrasanta                                                     0
University City                                                 3
Valley Center                                                   1
Vista                                                           4

                           Arts Entertainment and Recreation jobs  \
Neighborhood
Allied Gardens, Del Cerro                                       0
Alpine                                                          0
Balboa Park                                                     0
Bonita                                                          0
Bonsall                                                         0
...                                                           ...
Tecate                                                          0
Tierrasanta                                                     0
University City                                                 0
Valley Center                                                   1
Vista                                                           0

                           Accommodation and Food Services jobs  \
Neighborhood
Allied Gardens, Del Cerro                                     0
Alpine                                                        1
Balboa Park                                                   0
Bonita                                                        0
Bonsall                                                       0
...                                                         ...
Tecate                                                        0
Tierrasanta                                                   0
University City                                               5
Valley Center                                                 5
Vista                                                         1

                           Public Administration jobs  \
Neighborhood
Allied Gardens, Del Cerro                           1
Alpine                                              0
Balboa Park                                         0
Bonita                                              0
Bonsall                                             0
...                                               ...
Tecate                                              0
Tierrasanta                                         0
University City                                     0
Valley Center                                       1
Vista                                               5

                           Other Services (excluding Public Administration) jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                  0
Alpine                                                                     0
Balboa Park                                                                0
Bonita                                                                     0
Bonsall                                                                    0
...                                                                      ...
Tecate                                                                     0
Tierrasanta                                                                0
University City                                                            3
Valley Center                                                              2
Vista                                                                      4

                           Fast Food jobs  Median Salary
Neighborhood
Allied Gardens, Del Cerro               1        37566.0
Alpine                                  0        50394.0
Balboa Park                             0        31305.0
Bonita                                  0        35479.0
Bonsall                                 0        31305.0
...                                   ...            ...
Tecate                                  0        31900.0
Tierrasanta                             1        30450.0
University City                        10        37566.0
Valley Center                           0        36000.0
Vista                                   5        37954.5

[70 rows x 23 columns]

In [10]:
# Add a location column for geolocating in PowerBI
neighborhood_aggregates_df['Location ZIP Code'] = neighborhood_aggregates_df.index.to_series().apply(find_geolocation_ZIP_Code)
print(neighborhood_aggregates_df)

                           Job Openings  \
Neighborhood
Allied Gardens, Del Cerro            44
Alpine                               17
Balboa Park                           2
Bonita                                8
Bonsall                               3
...                                 ...
Tecate                                1
Tierrasanta                           5
University City                     108
Valley Center                        21
Vista                               158

                           Agriculture Forestry Fishing and Hunting jobs  \
Neighborhood
Allied Gardens, Del Cerro                                              0
Alpine                                                                 0
Balboa Park                                                            0
Bonita                                                                 0
Bonsall                                                                0
...                                                                  ...
Tecate                                                                 0
Tierrasanta                                                            0
University City                                                        0
Valley Center                                                          0
Vista                                                                  2

                           Mining Quarrying and Oil and Gas Extraction jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                 0
Alpine                                                                    1
Balboa Park                                                               0
Bonita                                                                    0
Bonsall                                                                   0
...                                                                     ...
Tecate                                                                    0
Tierrasanta                                                               0
University City                                                           0
Valley Center                                                             0
Vista                                                                     3

                           Utilities jobs  Construction jobs  \
Neighborhood
Allied Gardens, Del Cerro               1                  1
Alpine                                  0                  1
Balboa Park                             1                  0
Bonita                                  0                  0
Bonsall                                 0                  0
...                                   ...                ...
Tecate                                  0                  0
Tierrasanta                             0                  0
University City                         0                  7
Valley Center                           0                  0
Vista                                  11                  8

                           Manufacturing jobs  Wholesale Trade jobs  \
Neighborhood
Allied Gardens, Del Cerro                   1                     4
Alpine                                      0                     0
Balboa Park                                 0                     0
Bonita                                      0                     1
Bonsall                                     0                     0
...                                       ...                   ...
Tecate                                      0                     0
Tierrasanta                                 0                     1
University City                             0                    10
Valley Center                               1                     0
Vista                                      16                     8

                           Retail Trade jobs  \
Neighborhood
Allied Gardens, Del Cerro                  4
Alpine                                     5
Balboa Park                                1
Bonita                                     0
Bonsall                                    0
...                                      ...
Tecate                                     0
Tierrasanta                                0
University City                           13
Valley Center                              0
Vista                                     22

                           Transportation and Warehousing jobs  \
Neighborhood
Allied Gardens, Del Cerro                                    2
Alpine                                                       0
Balboa Park                                                  0
Bonita                                                       0
Bonsall                                                      0
...                                                        ...
Tecate                                                       1
Tierrasanta                                                  0
University City                                              2
Valley Center                                                0
Vista                                                        8

                           Information jobs  ...  \
Neighborhood                                 ...
Allied Gardens, Del Cerro                 0  ...
Alpine                                    0  ...
Balboa Park                               0  ...
Bonita                                    1  ...
Bonsall                                   0  ...
...                                     ...  ...
Tecate                                    0  ...
Tierrasanta                               1  ...
University City                           9  ...
Valley Center                             0  ...
Vista                                     5  ...

                           Administration & Support Waste Management and Remediation jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                  1
Alpine                                                                     1
Balboa Park                                                                0
Bonita                                                                     0
Bonsall                                                                    0
...                                                                      ...
Tecate                                                                     0
Tierrasanta                                                                1
University City                                                            0
Valley Center                                                              1
Vista                                                                      2

                           Educational Services jobs  \
Neighborhood
Allied Gardens, Del Cerro                          2
Alpine                                             0
Balboa Park                                        0
Bonita                                             2
Bonsall                                            3
...                                              ...
Tecate                                             0
Tierrasanta                                        0
University City                                    8
Valley Center                                      0
Vista                                              2

                           Health Care and Social Assistance jobs  \
Neighborhood
Allied Gardens, Del Cerro                                       9
Alpine                                                          0
Balboa Park                                                     0
Bonita                                                          0
Bonsall                                                         0
...                                                           ...
Tecate                                                          0
Tierrasanta                                                     0
University City                                                 3
Valley Center                                                   1
Vista                                                           4

                           Arts Entertainment and Recreation jobs  \
Neighborhood
Allied Gardens, Del Cerro                                       0
Alpine                                                          0
Balboa Park                                                     0
Bonita                                                          0
Bonsall                                                         0
...                                                           ...
Tecate                                                          0
Tierrasanta                                                     0
University City                                                 0
Valley Center                                                   1
Vista                                                           0

                           Accommodation and Food Services jobs  \
Neighborhood
Allied Gardens, Del Cerro                                     0
Alpine                                                        1
Balboa Park                                                   0
Bonita                                                        0
Bonsall                                                       0
...                                                         ...
Tecate                                                        0
Tierrasanta                                                   0
University City                                               5
Valley Center                                                 5
Vista                                                         1

                           Public Administration jobs  \
Neighborhood
Allied Gardens, Del Cerro                           1
Alpine                                              0
Balboa Park                                         0
Bonita                                              0
Bonsall                                             0
...                                               ...
Tecate                                              0
Tierrasanta                                         0
University City                                     0
Valley Center                                       1
Vista                                               5

                           Other Services (excluding Public Administration) jobs  \
Neighborhood
Allied Gardens, Del Cerro                                                  0
Alpine                                                                     0
Balboa Park                                                                0
Bonita                                                                     0
Bonsall                                                                    0
...                                                                      ...
Tecate                                                                     0
Tierrasanta                                                                0
University City                                                            3
Valley Center                                                              2
Vista                                                                      4

                           Fast Food jobs  Median Salary  Location ZIP Code
Neighborhood
Allied Gardens, Del Cerro               1        37566.0              92120
Alpine                                  0        50394.0              91901
Balboa Park                             0        31305.0              92134
Bonita                                  0        35479.0              91902
Bonsall                                 0        31305.0              92003
...                                   ...            ...                ...
Tecate                                  0        31900.0              91980
Tierrasanta                             1        30450.0              92124
University City                        10        37566.0              92122
Valley Center                           0        36000.0              92082
Vista                                   5        37954.5              92083

[70 rows x 24 columns]

In [11]:
# Remove Neighborhoods that have less than 5 job postings
neighborhood_aggregates_df = neighborhood_aggregates_df[neighborhood_aggregates_df["Job Openings"] > 4]
display(neighborhood_aggregates_df)

,Job Openings,Agriculture Forestry Fishing and Hunting jobs,Mining Quarrying and Oil and Gas Extraction jobs,Utilities jobs,Construction jobs,Manufacturing jobs,Wholesale Trade jobs,Retail Trade jobs,Transportation and Warehousing jobs,Information jobs,...,Administration & Support Waste Management and Remediation jobs,Educational Services jobs,Health Care and Social Assistance jobs,Arts Entertainment and Recreation jobs,Accommodation and Food Services jobs,Public Administration jobs,Other Services (excluding Public Administration) jobs,Fast Food jobs,Median Salary,Location ZIP Code
Neighborhood,,,,,,,,,,,,,,,,,,,,,
"Allied Gardens, Del Cerro",44,0,0,1,1,1,4,4,2,0,...,1,2,9,0,0,1,0,1,37566.000000,92120
Alpine,17,0,1,0,1,0,0,5,0,0,...,1,0,0,0,1,0,0,0,50394.000000,91901
Bonita,8,0,0,0,0,0,1,0,0,1,...,0,2,0,0,0,0,0,0,35479.000000,91902
Campo,6,0,0,0,1,0,0,1,1,0,...,0,0,1,0,0,0,0,1,35246.000000,91906
Cardiff,9,1,0,0,0,0,2,0,0,0,...,0,1,0,0,0,0,0,3,33392.000000,92007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spring Valley,37,0,0,1,3,1,2,6,1,0,...,0,0,5,0,0,1,2,0,36377.166667,91978
Tierrasanta,5,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,1,30450.000000,92124
University City,108,0,0,0,7,0,10,13,2,9,...,0,8,3,0,5,0,3,10,37566.000000,92122
Valley Center,21,0,0,0,0,1,0,0,0,0,...,1,0,1,1,5,1,2,0,36000.000000,92082
Vista,158,2,3,11,8,16,8,22,8,5,...,2,2,4,0,1,5,4,5,37954.500000,92083

In [13]:
# Save to .csv File

neighborhood_aggregates_df.to_csv('../Aggregates/Neighborhood_Aggregates_temp.csv')